---

name: Debug actions

on: [push]

jobs:
  Debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: CONTAINER ACTION
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
