---

name: Run DC NJS Actions

on: [push]

jobs:
  Debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: CONTAINER ACTION
        uses: ./.github/actions/docker-container-action
        with:
          who-to-greet: 'Mona the Octocat'

