name: Run Local Action Dad Joke

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: DAD JOKE
        uses: ./.github/actions/joke-action